boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'), # boards:index
    path('new/', views.new, name='new'), # /boards/new/
    # path('create/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/edit/', views.edit, name='edit'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete')
    # path('<int:board_pk>/update/', views.update, name='update'),
]

django_recrud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/models.py
from django.db import models

# Create your models here.
# 게시글
class Board(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'<Board({self.id}): {self.title}>'
        
# 댓글
class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    # on_delete는 참조하는 객체가 삭제될 경우 설정.
    # CASCADE : 같이 삭제
    # SET_NULL : NULL 값으로 변경(NOT NULL인 경우 불가능)
    # SET_DEFAULT : DEFAULT 값으로 변경(DEFAULT값 없으면 불가능)
    # PROTECT : 삭제 불가
    
    def __str__(self):
        return '<Board({self.board_id}): Comment({self.id}-{self.content})>'
        # 12번 글의 id가 1인 댓글
        # <Board(12) : Comment(1)>

boards/views.py
import pprint
from django.shortcuts import render, redirect
from .models import Board, Comment
# Create your views here.
def index(request):
    # pprint.pprint(request)
    # pprint.pprint(type(request))
    # pprint.pprint(dir(request))
    # print(request.scheme)
    # print(request.get_host())
    # print(request.get_full_path())
    # print(request.build_absolute_uri())
    # print(request.method)
    # pprint.pprint(request.META)
    boards = Board.objects.order_by('-id')
    return render(request, 'boards/index.html', {
        'boards': boards
    })
    
def new(request):
    if request.method == 'POST':
        board = Board()
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.image = request.FILES.get('image')
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        return render(request, 'boards/new.html')
    
# def create(request):
#     board = Board()
#     board.title = request.POST.get('title')
#     board.content = request.POST.get('content')
#     board.save()
#     return redirect('boards:detail', board.pk)

def detail(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    comments = board.comment_set.all()
    return render(request, 'boards/detail.html', {
        'board': board, 
        'comments' : comments,
    })
    
def delete(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.pk)

def edit(request, board_pk):
    if request.method == 'POST':
        board = Board.objects.get(pk=board_pk)
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        board = Board.objects.get(pk=board_pk)
        return render(request, 'boards/edit.html', {
            'board': board
        })

# def update(request, pk):
#     board = Board.objects.get(pk=pk)
#     board.title = request.POST.get('title')
#     board.content = request.POST.get('content')
#     board.save()
#     return redirect('boards:detail', board.pk)

def comments_create(request, board_pk):
    # 1. 댓글 달 게시물을 가져온다.
    board = Board.objects.get(pk=board_pk)
    # 2. 댓글을 저장한다.
    comment = Comment()
    comment.content = request.POST.get('content')
    comment.board = board
    comment.save()
    return redirect('boards:detail', board.pk)
    # return redirect('boards:detail', comment.board_id)와 동일

def comments_delete(request, board_pk, comment_pk):
    if request.method == 'POST':
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
    return redirect('boards:detail', board_pk)
    

boards/templates/boards/detail.html
<h1>{{ board.id }}번글</h1>
<hr>
<img src="{{ board.image.url }}">
<h2>{{ board.title }}</h2>
<p>{{ board.content }}</p>
<a href="{% url 'boards:index' %}">목록보기</a>
<form action="{% url 'boards:delete' board.pk %}" method="POST" style="display: inline" onsubmit="return confirm('삭제할거야?')">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>
<a href="{% url 'boards:edit' board.pk %}">수정</a>
<hr>
<p>댓글{{ comments.count }}개</p>
<p>댓글 작성</p>
<form action="{% url 'boards:comments_create' board.pk%}" method="POST">
    {% csrf_token %}
    <input name="content" type="text">
    <input type="submit">
</form>
{% for comment in comments %}
<li>{{ forloop.counter }} : {{ comment.content }}
    <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST" style="display: inline" onsubmit="return confirm('삭제할거야?')">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
</li>
{% empty %}
    <b><p>댓글이 없습니다.</p></b>
{% endfor %}

boards/templates/boards/edit.html
<form method="POST">
    {% csrf_token %}
    <input type="text" name="title" value="{{board.title}}"><br>
    <textarea name="content">{{board.content}}</textarea>
    <input type="submit">
</form>

boards/templates/boards/index.html
<!-- 상속을 받는다면 extends가 최상단 위치하기 -->
{% load static %}
<!--boards/bh.jpg-->
<img src="{% static 'bh.jpg' %}">
<h1>게시판</h1>
<a href="{% url 'boards:new' %}">글 작성하러가기</a>
{% for board in boards %}
    <p>{{ board.id }}</p>
    <p>{{ board.title }}</p>
    <a href="{% url 'boards:detail' board.pk %}">글 보기</a>
    <hr>
{% endfor %}

boards/templates/boards/new.html
<!--file upload를 위해서는 form에 enctype을 설정해줘야 한다.-->
<!--기본값은 application/x-www-form-urlencoded 이다.-->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title"><br>
    <textarea name="content"></textarea><br>
    <!--accept는 file 업로드시 확장자 제한을 하거나, audio, video, image 제한을 한다.-->
    <input type="file" name="image" accept="image/*"><br>
    <input type="submit">
</form>